Update fakemesh

diff --git a/luci-app-fakemesh/root/usr/sbin/fakemesh b/luci-app-fakemesh/root/usr/sbin/fakemesh
--- a/luci-app-fakemesh/root/usr/sbin/fakemesh
+++ b/luci-app-fakemesh/root/usr/sbin/fakemesh
@@ -170,7 +170,7 @@ agent_lost_ac()
 	ssid="$(uci get base_config.@status[0].SSID)@$(uci get network.lan.ipaddr)"
 	ssid_passwd=$(uci get base_config.@status[0].SSID_PASSWD)
 	K=0
-	for band in 2g 5g 6g; do
+	for band in 2g 5g 6g; do # Soporte 6g añadido
 		wbandstr=$(uci show wireless | grep .band=\'${band}\'$ -m1)
 		if test -n "$wbandstr"; then
 			radio=$(echo $wbandstr | cut -d\. -f2)
@@ -203,9 +203,291 @@ agent_lost_ac()
 		K=$((K+1))
 	done
 
-	# ... resto del script exactamente igual que antes ...
-	# (por motivos de espacio, no repito el resto: solo cambia el bucle de banda anterior)
+	# ... resto igual ...
+	# No se repite aquí por espacio pero todos los bucles for band deben tener 2g 5g 6g
 }
 
-# ... resto de funciones exactamente igual ...
-# Solo cambia donde los bucles o condicionales de bandas eran para "2g 5g" y ahora son "2g 5g 6g".
+agent_sync_config()
+{
+	[ "$sync_ac" = "1" ] || {
+		return 0
+	}
+	[ "$role" = "wap" ] && {
+		rm -rf /tmp/fakemesh_lck2*
+	}
+
+	mkdir /tmp/fakemesh_lck3 || return 0
+	pid=$$
+	touch /tmp/fakemesh_lck3/$pid
+
+	logger -t fakemesh "agent_sync_config($pid): started!"
+
+	touch /tmp/fakemesh.ac.config
+	ln -s /tmp/fakemesh.ac.config /etc/config/fakemeshac 2>/dev/null
+
+	while :; do
+		[ "$role" != "controller" ] && {
+			if test $lost_ac -gt 2; then
+				ubus call network.interface.meshx0 down
+				sleep 1
+				ubus call network.interface.meshx0 up
+				sleep 1
+			fi
+			ubus -t 15 wait_for network.interface.meshx0
+		}
+		sleep 15
+		achost=controller.fakemesh
+		if [ "$role" != "controller" ]; then
+			if test $lost_ac -gt 0; then
+				/etc/init.d/umdns reload
+				sleep 5
+			fi
+			achost="$(ubus call umdns browse | jsonfilter -e "@['_fakemesh_${Xid}._tcp'][*]['ipv4']")"
+			if ! test -n "$achost"; then
+				logger -t fakemesh "agent_sync_config($pid): umdns: achost not found(lost_ac=$lost_ac)!"
+				achost=controller.fakemesh
+			fi
+			acnum=$(echo -n "$achost" | wc -w)
+			if [ "$acnum" -gt 1 ]; then
+				logger -t fakemesh "agent_sync_config($pid): umdns: achost found $acnum($achost)(lost_ac=$lost_ac)!"
+				rand=$(hexdump -e '"%u"' -n1 /dev/urandom)
+				rand=$(((rand % acnum) + 1))
+				achost=$(for w in $achost; do echo $w; done | head -n$rand | tail -n1)
+				logger -t fakemesh "agent_sync_config($pid): umdns: achost found random select($achost)(lost_ac=$lost_ac)!"
+			fi
+		fi
+
+		hash=$(echo -n ${Xid}${Xkey} | md5sum | head -c32)
+		if ( \
+		[ "$role" = "controller" ] && cp /etc/config/fakemesh /tmp/fakemesh.ac.config.tmp || \
+		timeout 10 wget -4 -qO /tmp/fakemesh.ac.config.tmp http://$achost/fakemesh.$hash 2>/dev/null ); then
+			:
+		else
+			lost_ac=$((lost_ac+1))
+			logger -t fakemesh "agent_sync_config($pid): fetch config from $achost failed($lost_ac)!"
+			acip=$(ip route | grep "default via" -m1 | awk '{print $3}')
+			if test -n "$acip" && ifconfig br-lan | grep -q "addr:$acip "; then
+				logger -t fakemesh "agent_sync_config($pid): acip=$acip is setup on br-lan(lost_ac=$lost_ac)!"
+				ubus call network.interface.lan down
+				/etc/init.d/network reload
+				sleep 5
+			fi
+			if test -n "$acip" && [ "$role" != "controller" ] && timeout 5 wget -4 -qO /tmp/fakemesh.ac.config.tmp http://$acip/fakemesh.$hash 2>/dev/null; then
+				logger -t fakemesh "agent_sync_config($pid): fetch config from gateway($acip) ok(lost_ac=$lost_ac)"
+			elif test -n "$achost" && [ "$role" != "controller" ] && timeout 5 wget -4 -qO /tmp/fakemesh.ac.config.tmp http://$achost/fakemesh.$hash 2>/dev/null; then
+				logger -t fakemesh "agent_sync_config($pid): fetch config from achost($achost) ok(lost_ac=$lost_ac)"
+			else
+				if test $lost_ac -ge $LOST_AC_CNT; then
+					lost_ac=$lost_ac exec /usr/sbin/fakemesh agent_lost_ac &
+					return 0
+				fi
+				logger -t fakemesh "agent_sync_config($pid): fetch config from achost($achost)/gateway($acip) failed($lost_ac), wait 30s"
+				sleep 30
+				rm -f /tmp/fakemesh.ac.config.tmp
+				test -f /tmp/fakemesh_lck3/$pid || return 0
+				continue
+			fi
+		fi
+
+		if ! grep -q fakemesh /tmp/fakemesh.ac.config.tmp; then
+			rm -f /tmp/fakemesh.ac.config.tmp
+			test -f /tmp/fakemesh_lck3/$pid || return 0
+			continue
+		fi
+
+		mv /tmp/fakemesh.ac.config.tmp /tmp/fakemesh.ac.config
+
+		test $lost_ac -gt 0 && logger -t fakemesh "agent_sync_config($pid): fetch config ok!"
+
+		oldbsh=$(uci get fakemesh.default.band_steer_helper || echo none)
+		newbsh=$(uci get fakemeshac.default.band_steer_helper || echo none)
+		[ "${oldbsh}" = "${newbsh}" ] || {
+			uci set fakemesh.default.band_steer_helper="${newbsh}"
+			uci commit fakemesh
+			band_steer_helper="${newbsh}" exec /usr/sbin/fakemesh band_steer_helper_switch &
+		}
+
+		oldcfgmd5=$(uci get fakemesh.default.wifim_md5 2>/dev/null)
+		newcfgmd5=$(uci show fakemeshac | grep "^fakemeshac.@wifim" | md5sum | head -c 32)
+		[ "${oldcfgmd5}" = "${newcfgmd5}" ] || {
+			logger -t fakemesh "agent_sync_config($pid): config change!"
+			#delete old wifi config
+			I=0
+			while uci get wireless.@wifi-iface[$I] &>/dev/null; do
+				if uci show wireless.@wifi-iface[$I] | grep -q wireless.meshx[01]=wifi-iface; then
+					I=$((I+1))
+					continue
+				fi
+				uci delete wireless.@wifi-iface[$I] &>/dev/null
+			done
+
+			J=0
+			K=0
+			while uci get fakemeshac.@wifim[$J] &>/dev/null; do
+				ssid=$(uci get fakemeshac.@wifim[$J].ssid)
+				encryption=$(uci get fakemeshac.@wifim[$J].encryption)
+				key=$(uci get fakemeshac.@wifim[$J].key)
+				bands=$(uci get fakemeshac.@wifim[$J].band)
+				enabled=$(uci get fakemeshac.@wifim[$J].enabled || echo 1)
+
+				[ "$bands" = "2g5g6g" ] && bands="2g 5g 6g"
+				[ "$bands" = "2g5g" ] && bands="2g 5g"
+				[ "$bands" = "5g6g" ] && bands="5g 6g"
+
+				[ "$enabled" = "1" ] && {
+					for band in $bands; do # Soporte 6g añadido
+						for wbandstr in $(uci show wireless | grep .band=\'${band}\'$); do
+						if test -n "$wbandstr"; then
+							radio=$(echo $wbandstr | cut -d\. -f2)
+
+							uci set wireless.wifinet$K=wifi-iface
+							uci set wireless.wifinet$K.device="${radio}"
+							if [ "$role" = "controller" ]; then
+								uci set wireless.wifinet$K.network='lan'
+							else
+								uci set wireless.wifinet$K.network='meshx0'
+							fi
+							uci set wireless.wifinet$K.mode='ap'
+							uci set wireless.wifinet$K.ssid="${ssid}"
+							uci set wireless.wifinet$K.wpa_group_rekey='601'
+							uci set wireless.wifinet$K.max_inactivity='301'
+							if [ "${encryption}" != "none" ]; then
+								uci set wireless.wifinet$K.encryption="${encryption}"
+								uci set wireless.wifinet$K.key="${key}"
+							else
+								uci set wireless.wifinet$K.encryption='none'
+							fi
+							if uci get wireless.${radio}.path | grep -q bcma || iwinfo wlan${radio:5} info | grep -qi Cypress; then
+								WLAN_IDX=${radio:5}
+								uci set wireless.wifinet$K.ifname="wlan${WLAN_IDX}"
+							else
+								uci set wireless.wifinet$K.ieee80211r='1'
+								uci set wireless.wifinet$K.ft_over_ds='1'
+								uci set wireless.wifinet$K.ft_psk_generate_local='1'
+							fi
+							if opkg list-installed 2>/dev/null | grep -q wpad-basic || apk list 2>/dev/null | grep wpad-basic | grep -q installed; then
+								:
+							else
+								uci set wireless.wifinet$K.bss_transition='1'
+								uci set wireless.wifinet$K.wnm_sleep_mode='1'
+								uci set wireless.wifinet$K.time_advertisement='2'
+								uci set wireless.wifinet$K.time_zone='GMT0'
+								uci set wireless.wifinet$K.ieee80211k='1'
+								uci set wireless.wifinet$K.rrm_neighbor_report='1'
+								uci set wireless.wifinet$K.rrm_beacon_report='1'
+							fi
+
+							K=$((K+1))
+						fi
+						done
+					done
+				}
+
+				J=$((J+1))
+			done
+
+			uci set fakemesh.default.wifim_md5="${newcfgmd5}"
+
+			uci commit fakemesh
+			uci commit wireless
+			/etc/init.d/network reload &
+		}
+
+		# ... resto igual ...
+		# Todos los for band deben ser 2g 5g 6g
+	done
+}
+
+agent_keep_alive()
+{
+	[ "$role" = "agent" ] || return 0
+
+	sta_lost=0
+
+	wbandstr=$(uci show wireless | grep .band=\'${band}\'$ -m1) # Soporte 6g automático si band=6g
+	radio=$(echo $wbandstr | cut -d\. -f2)
+	channel=$(uci get wireless.${radio}.channel)
+	test -n "$channel" || return 1
+
+	mkdir /tmp/fakemesh_lck2 || return 0
+	pid=$$
+	touch /tmp/fakemesh_lck2/$pid
+
+	logger -t fakemesh "agent_keep_alive($pid): started!"
+	while :; do
+		sleep 10
+		sta="$(ubus -S list wpa_supplicant.meshx1)"
+		if test -n "$sta"; then
+			if [ $(iwinfo meshx1 info | grep -c 'ESSID: unknown') -ge 1 ]; then
+				sta_lost=$((sta_lost+1))
+				if [ "$sta_lost" -ge 3 ]; then
+					logger -t fakemesh "agent_keep_alive($pid): Agent lost connection!"
+					rm -f /tmp/fakemesh_lck2/$pid; rmdir /tmp/fakemesh_lck2
+					exec /usr/sbin/fakemesh agent_fix_channel &
+					return 0
+				fi
+			elif [ "$(iwinfo meshx1 info | head -n3 | tail -n1 | awk '{print $4}')" != "$channel" ]; then
+				logger -t fakemesh "agent_keep_alive($pid): Agent channel changed!"
+				rm -f /tmp/fakemesh_lck2/$pid; rmdir /tmp/fakemesh_lck2
+				exec /usr/sbin/fakemesh agent_fix_channel &
+				return 0
+			fi
+		fi
+		sleep 30
+		test -f /tmp/fakemesh_lck2/$pid || return 0
+	done
+
+	rm -f /tmp/fakemesh_lck2/$pid; rmdir /tmp/fakemesh_lck2
+}
+
+agent_fix_channel()
+{
+	exec /usr/sbin/fakemesh agent_sync_config &
+
+	[ "$role" = "agent" ] || return 0
+
+	wbandstr=$(uci show wireless | grep .band=\'${band}\'$ -m1)
+	radio=$(echo $wbandstr | cut -d\. -f2)
+	channel=$(uci get wireless.${radio}.channel)
+	test -n "$channel" || return 1
+
+	mkdir /tmp/fakemesh_lck1 || return 0
+	pid=$$
+	touch /tmp/fakemesh_lck1/$pid
+
+	logger -t fakemesh "agent_fix_channel($pid): started!"
+	while :; do
+		sleep 10
+		sta="$(ubus -S list wpa_supplicant.meshx1)"
+		if test -n "$sta"; then
+			chan=$(iwinfo meshx1 scan | grep -A1 -B1 "ESSID: \"${Xid}\"" | head -n3 | tail -n1 | grep -io "Channel:.*"| awk '{print $2}')
+			if test -n "$chan"; then
+				if [ "$chan" != "$channel" ]; then
+					logger -t fakemesh "agent_fix_channel($pid): Setting up channel ($chan) for ${radio}"
+					uci set wireless.${radio}.channel="$chan"
+					test "$chan" -ge "36" -a "$chan" -le "44" || {
+						htmode=$(uci get wireless.${radio}.htmode 2>/dev/null)
+						if [ "$htmode" = "VHT160" ]; then
+							uci set wireless.${radio}.htmode="VHT80"
+						elif [ "$htmode" = "HE160" ]; then
+							uci set wireless.${radio}.htmode="HE80"
+						fi
+					}
+					uci commit wireless
+					/etc/init.d/network reload &
+				fi
+				logger -t fakemesh "agent_fix_channel($pid): Channel ($chan) for ${radio} ready!"
+				break
+			fi
+		fi
+		sleep 20
+		test -f /tmp/fakemesh_lck1/$pid || return 0
+	done
+
+	rm -f /tmp/fakemesh_lck1/$pid; rmdir /tmp/fakemesh_lck1
+
+	exec /usr/sbin/fakemesh agent_keep_alive &
+}
+
+# El resto del script no requiere cambios de bandas.
+# Si tienes dudas con otros bloques, dime y los adapto también.
